# Generated by Django 5.2.5 on 2025-09-04 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.module', verbose_name='Module')),
                ('student', models.ForeignKey(limit_choices_to={'profil': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
    ]
