# Generated by Django 5.2.5 on 2025-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_assign_roles', 'Peut assigner des rôles aux utilisateurs')]},
        ),
    ]
