# Generated by Django 5.2.5 on 2025-09-12 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_date_of_birth_user_phone_number'),
    ]

    operations = [
        # 1. D'ABORD supprimer la contrainte unique_together existante
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        
        # 2. AJOUTER les nouveaux champs (d'abord week_start)
        migrations.AddField(
            model_name='timetable',
            name='week_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Début de semaine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Salle'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        
        # 3. MODIFIER les champs existants
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Lundi'), ('TUESDAY', 'Mardi'), ('WEDNESDAY', 'Mercredi'), ('THURSDAY', 'Jeudi'), ('FRIDAY', 'Vendredi'), ('SATURDAY', 'Samedi')], max_length=10, verbose_name='Jour'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'profil': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timeslot',
            field=models.CharField(choices=[('8-10', '8h-10h'), ('10-12', '10h-12h'), ('14-16', '14h-16h'), ('16-18', '16h-18h')], max_length=5, verbose_name='Créneau'),
        ),
        
        # 4. SUPPRIMER les anciens modèles/champs
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='week',
        ),
        
        # 5. ENFIN, ajouter la NOUVELLE contrainte unique_together
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('week_start', 'day', 'timeslot')},
        ),
        
        # 6. Modifier les options du modèle
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['week_start', 'day', 'timeslot'], 'permissions': [('can_manage_timetable', 'Peut gérer les emplois du temps'), ('can_publish_timetable', 'Peut publier les emplois du temps')], 'verbose_name': 'Emploi du temps', 'verbose_name_plural': 'Emplois du temps'},
        ),
    ]