# Generated by Django 5.2.5 on 2025-09-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('peut_acceder_module', 'Peut acceder au module'), ('peut_acceder_aux_eleve', 'Peut acceder aux eleves')]},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week_start',
            field=models.DateField(null=True, verbose_name='Début de semaine'),
        ),
    ]
