# Generated by Django 5.2.5 on 2025-09-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_timetable_week_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('peut_acceder_module', 'Peut acceder au module'), ('peut_acceder_aux_eleve', 'Peut acceder aux eleves'), ('peut_acceder_aux_enseigants', 'peut_acceder_aux_enseigants'), ('peut_acceder_aux_roles', 'peut_acceder_aux_roles')]},
        ),
    ]
