# Generated by Django 5.2.5 on 2025-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='cm_hours',
            field=models.FloatField(default=0, verbose_name='Heures de CM'),
        ),
        migrations.AddField(
            model_name='module',
            name='td_hours',
            field=models.FloatField(default=0, verbose_name='Heures de TD'),
        ),
        migrations.AddField(
            model_name='module',
            name='tp_hours',
            field=models.FloatField(default=0, verbose_name='Heures de TP'),
        ),
    ]
