# Generated by Django 5.2.5 on 2025-09-17 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'order', 'question'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('peut_acceder_module', 'Peut acceder au module'), ('peut_acceder_aux_eleve', 'Peut acceder aux eleves'), ('peut_acceder_aux_enseignants', 'peut acceder aux enseigants'), ('peut_acceder_aux_roles', 'peut acceder aux roles'), ('peut_acceder_au_dashboard', 'Peut accéder au tableau de bord '), ('dashboard', 'Peut voir les infos utiles  pour des étudiants'), ('peut_voir_infos_utile_teacher', 'Peut voir les infos utiles pour des enseignants'), ('peut_agir_infos_utile_student', 'Peut agir sur les infos utiles pour des étudiants'), ('peut_agir_infos_utile_teacher', 'Peut agir sur les infos utiles pour des enseignants'), ('can_view_student_performance_data', 'Peut voir ses données de performance  étudiants'), ('can_view_teacher_module_performance_data', 'Peut voir les données de performance des modules des enseignants'), ('can_view_all_students_performance_data ', 'Peut voir les données de performance de tous les étudiants'), ('can_view_student_list', 'Peut voir la liste des étudiants'), ('can_view_teacher_list', 'Peut voir la liste des enseignants'), ('can_view_module_list', 'Peut voir la liste des modules'), ('can_view_results_list', 'Peut voir la liste résultats'), ('can_view_suggestions_list', 'Peut voir la liste des suggestions'), ('can_view_module_details', "Peut les details d'un module"), ('can_view_student_details', "Peut voir les détails d'un étudiant"), ('can_view_teacher_details', "Peut voir les détails d'un enseignant"), ('can_view_own_details', 'Peut voir ses propres détails'), ('cans_view_results', 'Peut voir les résultats'), ('can_view_own_results', 'Peut voir ses propres résultats'), ('can_view_section__admin', "Peut voir la d'administration des section"), ('view_role', 'Peut voir les rôles'), ('add_role', 'Peut ajouter un rôle'), ('change_role', 'Peut modifier un rôle'), ('delete_role', 'Peut supprimer un rôle'), ('assign_role', 'Peut assigner des rôles'), ('view_timetable', "Peut voir l'emploi du temps"), ('manage_timetable', "Peut gérer l'emploi du temps"), ('can_add_teacher', 'Peut ajouter un enseignant'), ('can_add_student', 'Peut ajouter un étudiant'), ('can_change_teacher', 'Peut modifier un enseignant'), ('can_change_student', 'Peut modifier un étudiant'), ('can_delete_teacher', 'Peut supprimer un enseignant'), ('can_delete_student', 'Peut supprimer un étudiant'), ('can_view_schoolinfo', "Peut voir les informations de l'école"), ('can_add_schoolinfo', "Peut ajouter les informations de l'école"), ('can_change_schoolinfo', "Peut modifier les informations de l'école"), ('can_delete_schoolinfo', "Peut supprimer les informations de l'école")]},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('compte', 'Compte et Connexion'), ('notes', 'Notes et Résultats'), ('cours', 'Cours et Emploi du temps'), ('autres', 'Autres questions')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('compte', 'Compte et Connexion'), ('notes', 'Notes et Résultats'), ('cours', 'Cours et Emploi du temps'), ('autres', 'Autres questions')], max_length=50)),
                ('question', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question utilisateur',
                'verbose_name_plural': 'Questions utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
