# Generated by Django 5.2.5 on 2025-09-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_faq_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('peut_acceder_module', 'Peut acceder au module'), ('peut_acceder_aux_eleve', 'Peut acceder aux eleves'), ('peut_acceder_aux_enseignants', 'peut acceder aux enseigants'), ('peut_acceder_aux_roles', 'peut acceder aux roles'), ('peut_acceder_au_dashboard', 'Peut accéder au tableau de bord '), ('dashboard', 'Peut voir les infos utiles  pour des étudiants'), ('peut_voir_infos_utile_teacher', 'Peut voir les infos utiles pour des enseignants'), ('peut_agir_infos_utile_student', 'Peut agir sur les infos utiles pour des étudiants'), ('peut_agir_infos_utile_teacher', 'Peut agir sur les infos utiles pour des enseignants'), ('can_view_student_performance_data', 'Peut voir ses données de performance  étudiants'), ('can_view_teacher_module_performance_data', 'Peut voir les données de performance des modules des enseignants'), ('can_view_all_students_performance_data ', 'Peut voir les données de performance de tous les étudiants'), ('can_view_student_list', 'Peut voir la liste des étudiants'), ('can_view_teacher_list', 'Peut voir la liste des enseignants'), ('can_view_module_list', 'Peut voir la liste des modules'), ('can_view_results_list', 'Peut voir la liste résultats'), ('can_view_suggestions_list', 'Peut voir la liste des suggestions'), ('can_delete_result', 'Peut supprimer un résultat'), ('can_view_module_details', "Peut les details d'un module"), ('can_view_student_details', "Peut voir les détails d'un étudiant"), ('can_view_teacher_details', "Peut voir les détails d'un enseignant"), ('can_view_own_details', 'Peut voir ses propres détails'), ('cans_view_results', 'Peut voir les résultats'), ('can_view_own_results', 'Peut voir ses propres résultats'), ('can_view_section__admin', "Peut voir la d'administration des section"), ('view_role', 'Peut voir les rôles'), ('add_role', 'Peut ajouter un rôle'), ('change_role', 'Peut modifier un rôle'), ('delete_role', 'Peut supprimer un rôle'), ('assign_role', 'Peut assigner des rôles'), ('view_timetable', "Peut voir l'emploi du temps"), ('manage_timetable', "Peut gérer l'emploi du temps"), ('can_add_teacher', 'Peut ajouter un enseignant'), ('can_add_student', 'Peut ajouter un étudiant'), ('can_change_teacher', 'Peut modifier un enseignant'), ('can_change_student', 'Peut modifier un étudiant'), ('can_delete_teacher', 'Peut supprimer un enseignant'), ('can_delete_student', 'Peut supprimer un étudiant'), ('can_view_schoolinfo', "Peut voir les informations de l'école"), ('can_add_schoolinfo', "Peut ajouter les informations de l'école"), ('can_change_schoolinfo', "Peut modifier les informations de l'école"), ('can_delete_schoolinfo', "Peut supprimer les informations de l'école")]},
        ),
    ]
